# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: nf_ai_comms.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'nf_ai_comms.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11nf_ai_comms.proto\x12\x0bnf_ai_comms\"\x85\x03\n\x0fTaskObservation\x12\x10\n\x08\x65vent_id\x18\x01 \x01(\t\x12\x12\n\nevent_type\x18\x02 \x01(\t\x12\x15\n\rtimestamp_iso\x18\x03 \x01(\t\x12\x15\n\rpipeline_name\x18\x04 \x01(\t\x12\x14\n\x0cprocess_name\x18\x05 \x01(\t\x12\x13\n\x0btask_id_num\x18\x06 \x01(\x03\x12\x11\n\ttask_hash\x18\x07 \x01(\t\x12\x11\n\ttask_name\x18\x08 \x01(\t\x12\x11\n\tnative_id\x18\t \x01(\t\x12\x0e\n\x06status\x18\n \x01(\t\x12\x11\n\texit_code\x18\x0b \x01(\x05\x12\x13\n\x0b\x64uration_ms\x18\x0c \x01(\x03\x12\x13\n\x0brealtime_ms\x18\r \x01(\x03\x12\x13\n\x0b\x63pu_percent\x18\x0e \x01(\t\x12\x16\n\x0epeak_rss_bytes\x18\x0f \x01(\x03\x12\x17\n\x0fpeak_vmem_bytes\x18\x10 \x01(\x03\x12\x12\n\nread_bytes\x18\x11 \x01(\x03\x12\x13\n\x0bwrite_bytes\x18\x12 \x01(\x03\"s\n\x06\x41\x63tion\x12\x1c\n\x14observation_event_id\x18\x01 \x01(\t\x12\x11\n\taction_id\x18\x02 \x01(\t\x12\x16\n\x0e\x61\x63tion_details\x18\x03 \x01(\t\x12\x0f\n\x07success\x18\x04 \x01(\x08\x12\x0f\n\x07message\x18\x05 \x01(\t2]\n\x0f\x41iActionService\x12J\n\x13SendTaskObservation\x12\x1c.nf_ai_comms.TaskObservation\x1a\x13.nf_ai_comms.Action\"\x00\x42,\n\x1a\x63om.yourorg.bioflowml.grpcB\x0eNfAiCommsProtob\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'nf_ai_comms_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\032com.yourorg.bioflowml.grpcB\016NfAiCommsProto'
  _globals['_TASKOBSERVATION']._serialized_start=35
  _globals['_TASKOBSERVATION']._serialized_end=424
  _globals['_ACTION']._serialized_start=426
  _globals['_ACTION']._serialized_end=541
  _globals['_AIACTIONSERVICE']._serialized_start=543
  _globals['_AIACTIONSERVICE']._serialized_end=636
# @@protoc_insertion_point(module_scope)
