# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import nf_ai_comms_pb2 as nf__ai__comms__pb2

GRPC_GENERATED_VERSION = '1.71.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in nf_ai_comms_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class AiActionServiceStub(object):
    """The service definition for communication.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SendTaskObservation = channel.unary_unary(
                '/nf_ai_comms.AiActionService/SendTaskObservation',
                request_serializer=nf__ai__comms__pb2.TaskObservation.SerializeToString,
                response_deserializer=nf__ai__comms__pb2.Action.FromString,
                _registered_method=True)


class AiActionServiceServicer(object):
    """The service definition for communication.
    """

    def SendTaskObservation(self, request, context):
        """NfStateObserver sends a TaskObservation, AiActionStreamer replies with an Action.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AiActionServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'SendTaskObservation': grpc.unary_unary_rpc_method_handler(
                    servicer.SendTaskObservation,
                    request_deserializer=nf__ai__comms__pb2.TaskObservation.FromString,
                    response_serializer=nf__ai__comms__pb2.Action.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'nf_ai_comms.AiActionService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('nf_ai_comms.AiActionService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class AiActionService(object):
    """The service definition for communication.
    """

    @staticmethod
    def SendTaskObservation(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/nf_ai_comms.AiActionService/SendTaskObservation',
            nf__ai__comms__pb2.TaskObservation.SerializeToString,
            nf__ai__comms__pb2.Action.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
